- name: Install Nginx on hosts
  hosts: all
  become: true

  vars:
    ansible_user: your_username
    ansible_password: your_password

  tasks:
    - name: Update package list
      apt:
        update_cache: true
        upgrade: dist

    - name: Install Nginx
      apt:
        name: nginx
        state: present
